language: objective-c
osx_image: xcode8
script:
  - travis_retry xcodebuild clean test -project Compose.xcodeproj -scheme Compose -destination "platform=iOS Simulator,name=iPhone 7" -configuration Debug ONLY_ACTIVE_ARCH=NO

after_success:
  - bash <(curl -s https://codecov.io/bash)
